name: Run Tests

on:
  push:
    branches:
      - '**'
      - '!staging'

defaults:
  run:
    working-directory: ./src

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Copy .env.ci file for testing
      run: cp .env.ci .env.testing

    - name: Configure key for testing
      run: php artisan key:generate --env=testing

    - name: Clear Config
      run: php artisan config:clear

    - name: Clear Laravel Cache
      run: php artisan optimize:clear

    - name: Check .env.testing
      run: cat .env.testing

    - name: Wait for MySQL
      run: dockerize -wait tcp://mysql:3306 -timeout 1m

    - name: Run migrations
      run: php artisan migrate --env=testing

    - name: Run Tests
      run: php artisan test --parallel
