name: Run Tests

on:
  push:
    branches:
      - '**'
      - '!staging'

defaults:
  run:
    working-directory: ./src

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: be_crm_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist

    #- name: Copy .env file for testing
    #  run: cp .env.example .env.testing

    - name: Configure Laravel for testing
      run: |
        sed -i 's/DB_HOST=host.docker.internal/DB_HOST=mysql/' .env.testing
        sed -i 's/DB_USERNAME=root/DB_USERNAME=test_user/' .env.testing
        php artisan key:generate --env=testing

    - name: Clear Config
      run: php artisan config:clear

    - name: Clear Laravel Cache
      run: php artisan optimize:clear

    - name: Check .env.testing
      run: cat .env.testing

    - name: Run Tests
      run: php artisan test --env=testing
